# Supply Chain & Logistics Analytics

## Notebook 1 - Data Loading & Cleaning

This notebook focuses on loading all datasets, checking data quality, and preparing clean data for SQL analysis and Power BI dashboard development.


In this notebook, the datasets are loaded and checked for common data quality issues before moving to analysis.

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option("display.max_columns", None)

# Display more rows while exploring data
pd.set_option("display.max_rows", 100)

## Define Dataset Path

In [54]:
# Location of raw csv files
DATA_PATH = "../data/raw/"

## Load All Datasets

In [55]:
customers = pd.read_csv("../Dataset/customers.csv")
orders = pd.read_csv( "../Dataset/orders.csv")
products = pd.read_csv("../Dataset/products.csv")
suppliers = pd.read_csv("../Dataset/suppliers.csv")
warehouses = pd.read_csv("../Dataset/warehouses.csv")
inventory = pd.read_csv("../Dataset/inventory.csv")
shipments = pd.read_csv("../Dataset/shipments.csv")
returns = pd.read_csv("../Dataset/returns.csv")

## Verify Dataset Loading

In [56]:
datasets = {
    "Customers": customers,
    "Orders": orders,
    "Products": products,
    "Suppliers": suppliers,
    "Warehouses": warehouses,
    "Inventory": inventory,
    "Shipments": shipments,
    "Returns": returns
}

for name, df in datasets.items():
    print(f"{name:<12} : {df.shape[0]} rows × {df.shape[1]} columns")

Customers    : 800 rows × 4 columns
Orders       : 10000 rows × 7 columns
Products     : 120 rows × 5 columns
Suppliers    : 25 rows × 4 columns
Warehouses   : 8 rows × 3 columns
Inventory    : 960 rows × 4 columns
Shipments    : 10000 rows × 6 columns
Returns      : 802 rows × 4 columns

## Preview the Data

Let's take a quick look at each dataset before checking data quality.

## Quick Preview

Before performing any cleaning, let's inspect the datasets to understand their structure and available columns.

In [57]:
# Preview customer dataset
customers.head()

   customer_id customer_name region    segment
0            1    Customer_1  South     Retail
1            2    Customer_2   East  Wholesale
2            3    Customer_3   West  Corporate
3            4    Customer_4   West  Corporate
4            5    Customer_5  North     Retail

In [58]:
# Preview orders dataset
orders.head()

,order_id,order_date,customer_id,product_id,warehouse_id,quantity,unit_price
0,10001,2025-09-06,700,21,6,20,421.40
1,10002,2025-04-18,187,6,8,14,446.02
2,10003,2025-01-05,155,117,5,17,912.30
3,10004,2025-02-16,344,44,7,2,198.04
4,10005,2025-10-22,746,90,2,1,100.40

In [59]:
# Preview products dataset
products.head()

   product_id product_name     category  supplier_id  unit_cost
0           1    Product_1         Home           22        439
1           2    Product_2    Furniture           25        207
2           3    Product_3       Sports           16         30
3           4    Product_4  Electronics            9        128
4           5    Product_5       Office            6        576

In [60]:
# Preview suppliers dataset
suppliers.head()

   supplier_id supplier_name  country  rating
0            1    Supplier_1  Vietnam       3
1            2    Supplier_2  Germany       2
2            3    Supplier_3    India       2
3            4    Supplier_4  Vietnam       2
4            5    Supplier_5      UAE       3

In [61]:
# Preview warehouses dataset
warehouses.head()

   warehouse_id warehouse_city  capacity
0             1          Delhi     14593
1             2         Mumbai     12424
2             3      Bengaluru     10924
3             4      Hyderabad      9911
4             5        Kolkata      9070

In [62]:
# Preview inventory dataset
inventory.head()

   product_id  warehouse_id  stock_qty  reorder_level
0           1             1         35            138
1           1             2        635            179
2           1             3        618            209
3           1             4        272            196
4           1             5        416            275

In [63]:
# Preview shipments dataset
shipments.head()

,shipment_id,order_id,shipping_mode,delivery_date,delivery_status,shipping_cost
0,50001,10001,Road,2025-09-11,Delayed,14.54
1,50002,10002,Road,2025-04-25,Delivered,35.83
2,50003,10003,Air,2025-01-09,Delivered,38.81
3,50004,10004,Rail,2025-02-24,Delivered,40.65
4,50005,10005,Road,2025-10-30,Delivered,7.91

In [64]:
# Preview returns dataset
returns.head()

   return_id  order_id  return_reason  returned_qty
0       9001     10004        Damaged             1
1       9002     10015  Late Delivery             6
2       9003     10020        Damaged             5
3       9004     10043  Late Delivery             1
4       9005     10056  Late Delivery             6

## Dataset Information

Checking the structure of each dataset including data types, null values, and memory usage.

In [65]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    800 non-null    int64
 1   customer_name  800 non-null    object
 2   region         800 non-null    object
 3   segment        800 non-null    object
dtypes: int64(1), object(3)
memory usage: 25.1+ KB

In [66]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10000 non-null  int64
 1   order_date    10000 non-null  object
 2   customer_id   10000 non-null  int64
 3   product_id    10000 non-null  int64
 4   warehouse_id  10000 non-null  int64
 5   quantity      10000 non-null  int64
 6   unit_price    10000 non-null  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 547.0+ KB

In [67]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    120 non-null    int64
 1   product_name  120 non-null    object
 2   category      120 non-null    object
 3   supplier_id   120 non-null    int64
 4   unit_cost     120 non-null    int64
dtypes: int64(3), object(2)
memory usage: 4.8+ KB

In [68]:
suppliers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   supplier_id    25 non-null     int64
 1   supplier_name  25 non-null     object
 2   country        25 non-null     object
 3   rating         25 non-null     int64
dtypes: int64(2), object(2)
memory usage: 932.0+ bytes

In [69]:
warehouses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   warehouse_id    8 non-null      int64
 1   warehouse_city  8 non-null      object
 2   capacity        8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

## Remaining Dataset Information

In [70]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     960 non-null    int64
 1   warehouse_id   960 non-null    int64
 2   stock_qty      960 non-null    int64
 3   reorder_level  960 non-null    int64
dtypes: int64(4)
memory usage: 30.1 KB

In [71]:
shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   shipment_id      10000 non-null  int64
 1   order_id         10000 non-null  int64
 2   shipping_mode    10000 non-null  object
 3   delivery_date    10000 non-null  object
 4   delivery_status  10000 non-null  object
 5   shipping_cost    10000 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.9+ KB

In [72]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 802 entries, 0 to 801
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      802 non-null    int64
 1   order_id       802 non-null    int64
 2   return_reason  802 non-null    object
 3   returned_qty   802 non-null    int64
dtypes: int64(3), object(1)
memory usage: 25.2+ KB

## Summary Statistics

Let's review the numerical columns available in each dataset.

In [73]:
for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(name.upper())
    print('='*60)
    display(df.describe(include="all"))

============================================================
CUSTOMERS
============================================================

        customer_id customer_name region segment
count      800.0000           800    800     800
unique          NaN           800      4       3
top             NaN    Customer_1  South  Retail
freq            NaN             1    216     296
mean       400.5000           NaN    NaN     NaN
std        231.0844           NaN    NaN     NaN
min          1.0000           NaN    NaN     NaN
25%        200.7500           NaN    NaN     NaN
50%        400.5000           NaN    NaN     NaN
75%        600.2500           NaN    NaN     NaN
max        800.0000           NaN    NaN     NaN

============================================================
ORDERS
============================================================

,order_id,order_date,customer_id,product_id,warehouse_id,quantity,unit_price
count,10000.00000,10000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,365,NaN,NaN,NaN,NaN,NaN
top,NaN,2025-12-13,NaN,NaN,NaN,NaN,NaN
freq,NaN,41,NaN,NaN,NaN,NaN,NaN
mean,15000.50000,NaN,399.540700,59.95840,4.489500,13.134500,484.444914
std,2886.89568,NaN,229.708054,34.48502,2.286966,7.190659,298.030658
min,10001.00000,NaN,1.000000,1.00000,1.000000,1.000000,31.250000
25%,12500.75000,NaN,201.000000,30.00000,2.000000,7.000000,228.822500
50%,15000.50000,NaN,396.000000,59.00000,4.000000,13.000000,438.090000
75%,17500.25000,NaN,597.000000,89.00000,6.000000,19.000000,719.242500
max,20000.00000,NaN,800.000000,120.00000,8.000000,25.000000,1257.510000

============================================================
PRODUCTS
============================================================

        product_id product_name category  supplier_id   unit_cost
count   120.000000          120      120   120.000000  120.000000
unique         NaN          120        5          NaN         NaN
top            NaN    Product_1   Sports          NaN         NaN
freq           NaN            1       32          NaN         NaN
mean     60.500000          NaN      NaN    13.008333  280.166667
std      34.785054          NaN      NaN     6.880121  168.109775
min       1.000000          NaN      NaN     1.000000   24.000000
25%      30.750000          NaN      NaN     7.000000  130.250000
50%      60.500000          NaN      NaN    13.000000  257.000000
75%      90.250000          NaN      NaN    18.250000  435.250000
max     120.000000          NaN      NaN    25.000000  600.000000

============================================================
SUPPLIERS
============================================================

        supplier_id supplier_name country     rating
count     25.000000            25      25  25.000000
unique          NaN            25       5        NaN
top             NaN    Supplier_1   India        NaN
freq            NaN             1       8        NaN
mean      13.000000           NaN     NaN   3.120000
std        7.359801           NaN     NaN   1.201388
min        1.000000           NaN     NaN   2.000000
25%        7.000000           NaN     NaN   2.000000
50%       13.000000           NaN     NaN   3.000000
75%       19.000000           NaN     NaN   4.000000
max       25.000000           NaN     NaN   5.000000

============================================================
WAREHOUSES
============================================================

        warehouse_id warehouse_city      capacity
count        8.00000              8      8.000000
unique           NaN              8           NaN
top              NaN          Delhi           NaN
freq             NaN              1           NaN
mean         4.50000            NaN  12416.750000
std          2.44949            NaN   3626.571216
min          1.00000            NaN   7945.000000
25%          2.75000            NaN   9700.750000
50%          4.50000            NaN  11674.000000
75%          6.25000            NaN  15057.750000
max          8.00000            NaN  18015.000000

============================================================
INVENTORY
============================================================

       product_id  warehouse_id   stock_qty  reorder_level
count  960.000000    960.000000  960.000000     960.000000
mean    60.500000      4.500000  396.134375     199.390625
std     34.657869      2.292482  221.414605      57.572084
min      1.000000      1.000000   21.000000     100.000000
25%     30.750000      2.750000  203.000000     151.000000
50%     60.500000      4.500000  392.000000     196.500000
75%     90.250000      6.250000  586.000000     248.000000
max    120.000000      8.000000  800.000000     300.000000

============================================================
SHIPMENTS
============================================================

,shipment_id,order_id,shipping_mode,delivery_date,delivery_status,shipping_cost
count,10000.00000,10000.00000,10000,10000,10000,10000.000000
unique,NaN,NaN,3,372,2,NaN
top,NaN,NaN,Rail,2025-08-06,Delivered,NaN
freq,NaN,NaN,3378,47,7512,NaN
mean,55000.50000,15000.50000,NaN,NaN,NaN,27.475066
std,2886.89568,2886.89568,NaN,NaN,NaN,13.035532
min,50001.00000,10001.00000,NaN,NaN,NaN,5.000000
25%,52500.75000,12500.75000,NaN,NaN,NaN,16.115000
50%,55000.50000,15000.50000,NaN,NaN,NaN,27.565000
75%,57500.25000,17500.25000,NaN,NaN,NaN,38.740000
max,60000.00000,20000.00000,NaN,NaN,NaN,49.990000

============================================================
RETURNS
============================================================

          return_id      order_id  return_reason  returned_qty
count    802.000000    802.000000            802    802.000000
unique          NaN           NaN              3           NaN
top             NaN           NaN  Late Delivery           NaN
freq            NaN           NaN            274           NaN
mean    9401.500000  15173.123441            NaN      6.967581
std      231.661751   2926.285618            NaN      5.453144
min     9001.000000  10004.000000            NaN      1.000000
25%     9201.250000  12605.000000            NaN      2.000000
50%     9401.500000  15293.500000            NaN      6.000000
75%     9601.750000  17709.750000            NaN     10.000000
max     9802.000000  19998.000000            NaN     25.000000

## Missing Values

In [74]:
missing_values = pd.DataFrame({
    "Missing Values": customers.isnull().sum(),
    "Percentage": round((customers.isnull().sum()/len(customers))*100,2)
})

missing_values

               Missing Values  Percentage
customer_id                 0         0.0
customer_name               0         0.0
region                      0         0.0
segment                     0         0.0

In [75]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.isnull().sum())

Customers

customer_id      0
customer_name    0
region           0
segment          0
dtype: int64

Orders

order_id        0
order_date      0
customer_id     0
product_id      0
warehouse_id    0
quantity        0
unit_price      0
dtype: int64

Products

product_id      0
product_name    0
category        0
supplier_id     0
unit_cost       0
dtype: int64

Suppliers

supplier_id      0
supplier_name    0
country          0
rating           0
dtype: int64

Warehouses

warehouse_id      0
warehouse_city    0
capacity          0
dtype: int64

Inventory

product_id       0
warehouse_id     0
stock_qty        0
reorder_level    0
dtype: int64

Shipments

shipment_id        0
order_id           0
shipping_mode      0
delivery_date      0
delivery_status    0
shipping_cost      0
dtype: int64

Returns

return_id        0
order_id         0
return_reason    0
returned_qty     0
dtype: int64

## Duplicate Records

In [76]:
for name, df in datasets.items():
    print(f"{name:<12} : {df.duplicated().sum()} duplicate rows")

Customers    : 0 duplicate rows
Orders       : 0 duplicate rows
Products     : 0 duplicate rows
Suppliers    : 0 duplicate rows
Warehouses   : 0 duplicate rows
Inventory    : 0 duplicate rows
Shipments    : 0 duplicate rows
Returns      : 0 duplicate rows

### Initial Observations

- Dataset loading completed successfully.
- Data types look consistent across most tables.
- Missing values and duplicates have been identified.
- The next step is to clean and standardize the datasets before analysis.

In [77]:
# Save current copies before cleaning (optional backup)

customers_raw = customers.copy()
orders_raw = orders.copy()
products_raw = products.copy()
suppliers_raw = suppliers.copy()
warehouses_raw = warehouses.copy()
inventory_raw = inventory.copy()
shipments_raw = shipments.copy()
returns_raw = returns.copy()

## Summary Statistics

Let's review the numerical and categorical information available in each dataset.

In [78]:
for name, df in datasets.items():
    print("=" * 70)
    print(f"{name.upper()} DATASET")
    print("=" * 70)

    display(df.describe(include="all"))

======================================================================
CUSTOMERS DATASET
======================================================================

        customer_id customer_name region segment
count      800.0000           800    800     800
unique          NaN           800      4       3
top             NaN    Customer_1  South  Retail
freq            NaN             1    216     296
mean       400.5000           NaN    NaN     NaN
std        231.0844           NaN    NaN     NaN
min          1.0000           NaN    NaN     NaN
25%        200.7500           NaN    NaN     NaN
50%        400.5000           NaN    NaN     NaN
75%        600.2500           NaN    NaN     NaN
max        800.0000           NaN    NaN     NaN

======================================================================
ORDERS DATASET
======================================================================

,order_id,order_date,customer_id,product_id,warehouse_id,quantity,unit_price
count,10000.00000,10000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,365,NaN,NaN,NaN,NaN,NaN
top,NaN,2025-12-13,NaN,NaN,NaN,NaN,NaN
freq,NaN,41,NaN,NaN,NaN,NaN,NaN
mean,15000.50000,NaN,399.540700,59.95840,4.489500,13.134500,484.444914
std,2886.89568,NaN,229.708054,34.48502,2.286966,7.190659,298.030658
min,10001.00000,NaN,1.000000,1.00000,1.000000,1.000000,31.250000
25%,12500.75000,NaN,201.000000,30.00000,2.000000,7.000000,228.822500
50%,15000.50000,NaN,396.000000,59.00000,4.000000,13.000000,438.090000
75%,17500.25000,NaN,597.000000,89.00000,6.000000,19.000000,719.242500
max,20000.00000,NaN,800.000000,120.00000,8.000000,25.000000,1257.510000

======================================================================
PRODUCTS DATASET
======================================================================

        product_id product_name category  supplier_id   unit_cost
count   120.000000          120      120   120.000000  120.000000
unique         NaN          120        5          NaN         NaN
top            NaN    Product_1   Sports          NaN         NaN
freq           NaN            1       32          NaN         NaN
mean     60.500000          NaN      NaN    13.008333  280.166667
std      34.785054          NaN      NaN     6.880121  168.109775
min       1.000000          NaN      NaN     1.000000   24.000000
25%      30.750000          NaN      NaN     7.000000  130.250000
50%      60.500000          NaN      NaN    13.000000  257.000000
75%      90.250000          NaN      NaN    18.250000  435.250000
max     120.000000          NaN      NaN    25.000000  600.000000

======================================================================
SUPPLIERS DATASET
======================================================================

        supplier_id supplier_name country     rating
count     25.000000            25      25  25.000000
unique          NaN            25       5        NaN
top             NaN    Supplier_1   India        NaN
freq            NaN             1       8        NaN
mean      13.000000           NaN     NaN   3.120000
std        7.359801           NaN     NaN   1.201388
min        1.000000           NaN     NaN   2.000000
25%        7.000000           NaN     NaN   2.000000
50%       13.000000           NaN     NaN   3.000000
75%       19.000000           NaN     NaN   4.000000
max       25.000000           NaN     NaN   5.000000

======================================================================
WAREHOUSES DATASET
======================================================================

        warehouse_id warehouse_city      capacity
count        8.00000              8      8.000000
unique           NaN              8           NaN
top              NaN          Delhi           NaN
freq             NaN              1           NaN
mean         4.50000            NaN  12416.750000
std          2.44949            NaN   3626.571216
min          1.00000            NaN   7945.000000
25%          2.75000            NaN   9700.750000
50%          4.50000            NaN  11674.000000
75%          6.25000            NaN  15057.750000
max          8.00000            NaN  18015.000000

======================================================================
INVENTORY DATASET
======================================================================

       product_id  warehouse_id   stock_qty  reorder_level
count  960.000000    960.000000  960.000000     960.000000
mean    60.500000      4.500000  396.134375     199.390625
std     34.657869      2.292482  221.414605      57.572084
min      1.000000      1.000000   21.000000     100.000000
25%     30.750000      2.750000  203.000000     151.000000
50%     60.500000      4.500000  392.000000     196.500000
75%     90.250000      6.250000  586.000000     248.000000
max    120.000000      8.000000  800.000000     300.000000

======================================================================
SHIPMENTS DATASET
======================================================================

,shipment_id,order_id,shipping_mode,delivery_date,delivery_status,shipping_cost
count,10000.00000,10000.00000,10000,10000,10000,10000.000000
unique,NaN,NaN,3,372,2,NaN
top,NaN,NaN,Rail,2025-08-06,Delivered,NaN
freq,NaN,NaN,3378,47,7512,NaN
mean,55000.50000,15000.50000,NaN,NaN,NaN,27.475066
std,2886.89568,2886.89568,NaN,NaN,NaN,13.035532
min,50001.00000,10001.00000,NaN,NaN,NaN,5.000000
25%,52500.75000,12500.75000,NaN,NaN,NaN,16.115000
50%,55000.50000,15000.50000,NaN,NaN,NaN,27.565000
75%,57500.25000,17500.25000,NaN,NaN,NaN,38.740000
max,60000.00000,20000.00000,NaN,NaN,NaN,49.990000

======================================================================
RETURNS DATASET
======================================================================

          return_id      order_id  return_reason  returned_qty
count    802.000000    802.000000            802    802.000000
unique          NaN           NaN              3           NaN
top             NaN           NaN  Late Delivery           NaN
freq            NaN           NaN            274           NaN
mean    9401.500000  15173.123441            NaN      6.967581
std      231.661751   2926.285618            NaN      5.453144
min     9001.000000  10004.000000            NaN      1.000000
25%     9201.250000  12605.000000            NaN      2.000000
50%     9401.500000  15293.500000            NaN      6.000000
75%     9601.750000  17709.750000            NaN     10.000000
max     9802.000000  19998.000000            NaN     25.000000

## Unique Values

In [81]:
for name, df in datasets.items():

    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    display(df.nunique().sort_values())

======================================================================
CUSTOMERS
======================================================================

segment            3
region             4
customer_id      800
customer_name    800
dtype: int64

======================================================================
ORDERS
======================================================================

warehouse_id        8
quantity           25
product_id        120
order_date        365
customer_id       800
unit_price       9526
order_id        10000
dtype: int64

======================================================================
PRODUCTS
======================================================================

category          5
supplier_id      25
unit_cost       107
product_id      120
product_name    120
dtype: int64

======================================================================
SUPPLIERS
======================================================================

rating            4
country           5
supplier_id      25
supplier_name    25
dtype: int64

======================================================================
WAREHOUSES
======================================================================

warehouse_id      8
warehouse_city    8
capacity          8
dtype: int64

======================================================================
INVENTORY
======================================================================

warehouse_id       8
product_id       120
reorder_level    199
stock_qty        549
dtype: int64

======================================================================
SHIPMENTS
======================================================================

delivery_status        2
shipping_mode          3
delivery_date        372
shipping_cost       4015
shipment_id        10000
order_id           10000
dtype: int64

======================================================================
RETURNS
======================================================================

return_reason      3
returned_qty      25
return_id        802
order_id         802
dtype: int64

## Standardize Data Types

In [82]:
# Convert date columns

orders["order_date"] = pd.to_datetime(orders["order_date"])

shipments["delivery_date"] = pd.to_datetime(
    shipments["delivery_date"]
)

## Verify Updated Data Types

In [83]:
print(orders.dtypes)

print("-" * 60)

print(shipments.dtypes)

order_id                 int64
order_date      datetime64[ns]
customer_id              int64
product_id               int64
warehouse_id             int64
quantity                 int64
unit_price             float64
dtype: object
------------------------------------------------------------
shipment_id                 int64
order_id                    int64
shipping_mode              object
delivery_date      datetime64[ns]
delivery_status            object
shipping_cost             float64
dtype: object

## Verify Updated Data Types

## Key Takeaways

- All datasets were loaded successfully without any loading issues.
- The overall data quality is good, with very few missing or duplicate records.
- Date columns were converted to the appropriate format for future analysis.
- The datasets are now clean and ready for exploratory data analysis (EDA), where trends, patterns, and business insights will be identified.

## Conclusion

The datasets were successfully prepared for analysis. Initial inspection shows that the data is well-structured with minimal quality issues. Since the raw data is now validated and organized, the next step is to explore trends, identify patterns, and generate business insights through exploratory data analysis.